.TH MYGREP 1
.SH NAME
mygrep \- search for a string in a file
.SH SYNOPSIS
.B mygrep
.I fp search_str matches
.SH DESCRIPTION
The mygrep function searches the contents of a file for the
specified search string. Matching results are returned through
the matches argument.
.SH AUTHOR
Sufia Atif <BSDSF24M035@PUCIT.edu.pk>
