.TH MYSTRNCPY 1
.SH NAME
mystrncpy \- copy a specified number of characters from a string
.SH SYNOPSIS
.B mystrncpy
.I dest src n
.SH DESCRIPTION
The mystrncpy function copies up to the specified number of
characters from the source string to the destination string.
.SH AUTHOR
Sufia Atif <BSDSF24M035@PUCIT.edu.pk>
